### ISSUE TITLE
[Bug]: Assets used in the slides are not tracked and saved

### ISSUE THREAD

**Issue by HongleiXie** [UofT-DSI/applying_statistical_concepts#94]
### Describe your issue

Currently all assets including pictures used in all slides are not saved within the repo therefore when I  re-generate the slides all images/gif are all gone.
Examples:
`[KNN_distance]: ../DSI%20Certificate%20Coordinator/KNN_distance.jpg`
`[KNN_Nearest]: ../DSI%20Certificate%20Coordinator/KNN_Nearest.png`

### Steps to reproduce

Go to any one of markdown files such as `Classification_I.md` and generate the slides

**Comment by danielrazavi** [comment]
acknowledged, will address in the upcoming commits

**Comment by danielrazavi** [comment]
Assets are now saved in a directory called [./01_materials/notebooks/images/](https://github.com/UofT-DSI/applying_statistical_concepts/tree/Edits/01_materials/notebooks/images)
